//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWinForm.Properties {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
        "System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager(
                        "BaiTapLonWinForm.Properties.Resources",
                        typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static System.Drawing.Bitmap backgroud_default =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("backgroud-default", resourceCulture)));

        public static System.Drawing.Bitmap calendar_star =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("calendar-star", resourceCulture)));

        public static System.Drawing.Bitmap default_user =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("default_user", resourceCulture)));

        public static System.Drawing.Bitmap login_iluustrator =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("login-iluustrator", resourceCulture)));

        public static System.Drawing.Bitmap logo_login =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("logo-login", resourceCulture)));

        public static System.Drawing.Bitmap logout_icon =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("logout-icon", resourceCulture)));

        public static System.Drawing.Bitmap logout_red =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("logout-red", resourceCulture)));

        public static System.Drawing.Bitmap myCalendar =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("myCalendar", resourceCulture)));

        public static System.Drawing.Bitmap myClass =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("myClass", resourceCulture)));

        public static System.Drawing.Bitmap register_illustrator =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("register-illustrator", resourceCulture)));

        public static System.Drawing.Bitmap Screenshot_2025_12_05_160540 =>
            ((System.Drawing.Bitmap)(ResourceManager.GetObject("Screenshot 2025-12-05 160540", resourceCulture)));
    }
}
